apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx

spec:

  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
      type: frontend

  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        type: frontend

    spec:
      containers:
        - name: nginx-container
          #imagePullPolicy: Always
          image: babaknasrolahy/project4-nginx:latest
          ports:
            - containerPort: 80


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python-app
    type: main

spec:

  replicas: 1
  selector:
    matchLabels:
      app: python-app
      type: main

  template:
    metadata:
      name: python-pod
      labels:
        app: python-app
        type: main

    spec:

      containers:
        - name: python-container
          #imagePullPolicy: Always
          image: babaknasrolahy/project4-python:latest
          ports:
           - containerPort: 5000


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-app
    type: db

spec:

  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
      type: db

  template:
     metadata:
        name: mysql-pod
        labels:
          app: mysql-app
          type: db

     spec:
        containers:
        - name: mysql-container
          image: mysql:5.7
          securityContext:
            runAsUser: 0
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: "babak13830"
              #valueFrom:
                #secretKeyRef:
                 # name: db-password
                  #key: password
          ports:
           - containerPort: 3306



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis-app
    type: db

spec:

  replicas: 1
  selector:
    matchLabels:
      app: redis-app
      type: db


  template:
    metadata:
      name: redis-pod
      labels:
        app: redis-app
        type: db


    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379


---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker-app
    type: worker

spec:

  replicas: 1
  selector:
    matchLabels:
      app: worker-app
      type: worker

  template:
    metadata:
      name: worker-pod
      labels:
        app: worker-app
        type: worker

    spec:
      containers:
      - name: worker-container
        imagePullPolicy: Always
        image: babaknasrolahy/project4-worker:latest
        env:
           - name: "db_password"
             valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
        ports:
          - containerPort: 5005



